### ISSUE TITLE
第一步就不行了

### ISSUE THREAD

**Issue by gao888** [Hexmagic/Baidu-Index#1]
根本登陆不了呀
[I 181101 11:41:37 baidu:39] 跳转到登录页
[I 181101 11:41:40 baidu:42] 点击弹出登录框
Traceback (most recent call last):
  File "C:/Users/laogao/Desktop/py study/Baidu-Index-master/app.py", line 9, in <module>
    bd.login(username, password)
  File "C:\Users\laogao\Desktop\py study\Baidu-Index-master\channel\baidu.py", line 43, in login
    self.driver.find_element_by_id("TANGRAM__PSP_4__userName").clear()
  File "C:\Users\laogao\AppData\Local\Programs\Python\Python37-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 360, in find_element_by_id
    return self.find_element(by=By.ID, value=id_)
  File "C:\Users\laogao\AppData\Local\Programs\Python\Python37-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "C:\Users\laogao\AppData\Local\Programs\Python\Python37-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\laogao\AppData\Local\Programs\Python\Python37-32\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"id","selector":"TANGRAM__PSP_4__userName"}
  (Session info: headless chrome=69.0.3497.100)
  (Driver info: chromedriver=2.43.600210 (68dcf5eebde37173d4027fa8635e332711d2874a),platform=Windows NT 10.0.17134 x86_64)

**Comment by Hexmagic** [comment]
你这个是没有获取到元素，禁用headless看一下，有可能是页面的元素还没有渲染成共就进行了点击，你可以增加sleep或者使用
while:
       try:
             ...
       except:
             time.sleep(1)

这个可能于网速有关

**Comment by gao888** [comment]
感谢大神指导，我延迟了4秒就好了，应该就是网速问题（身在国外），但是后面的res2那里又出来问题

Traceback (most recent call last):
  File "C:/Users/laogao/Desktop/py study/Baidu-Index-master/app.py", line 15, in <module>
    rst = bd.search(word, start, end)
  File "C:\Users\laogao\Desktop\py study\Baidu-Index-master\channel\baidu.py", line 98, in search
    res2 = self.get_res2(text)
  File "C:\Users\laogao\Desktop\py study\Baidu-Index-master\channel\baidu.py", line 193, in get_res2
    '//script[contains(text(),"res2")]/text()')[0].replace('\r', '')
IndexError: list index out of range

我之前用longxiaofei spider-BaiduIndex的时候也是get res2这里出了问题，现在在国内用是没有这些问题的吗？

**Comment by Hexmagic** [comment]
这个是登录的问题 我对登录没有检验，百度的登录很坑，可能需要验证码和手机验证码，你可以手动登录账号看是否出现了验证码，登录成功后再次测试登录是否需要验证码，如果不需要，那就ok了，再次运行脚本就行，我本地是这样解决的。登录的地方没有考虑验证码的问题，因为牵涉到图片是被和手机验证码所以没有做，如果上面的办法没有解决问题，建议你写个登录脚本使用selenium去登录，然后获取cookie进行保存，修改代码直接使用cookie而非模拟浏览器登录即可,这样做的问题是可能需要定期去更新cookie文件以及重启脚本，但是百度的cookie有效性一般还是很长的。当然你可以嵌入其他非模拟浏览器登录代码，一样有可能需要验证码。

**Comment by gao888** [comment]
十分感激！！！我自己手动复制cookie就解决了！！
